extensions: {}
cabal-file: project.cabal
version: 1
module-template: ! 'module MODULE_NAME where

'
modules:
  Main(src/Main.hs):
    target-type: console
    filename: src/Main.hs
  Scrapper:
    filename: src/Scrapper.hs
